### ISSUE TITLE
help

### ISSUE THREAD

**Issue by pupupu-p** [Lcrypto/BP-decoder-for-NB_LDPC-codes#2]
I am new to non-binary LDPC research,When I want to use the H matrix I constructed on GF(8) to run this program, I get an error:
ERROR: GF order(64) does not match with matrix file (8)
I did not find where to modify this error in the program,hope to get your reply as soon as possible

**Comment by Lcrypto** [comment]
Hi, just recompile mex file of decoder  with Q=3 for GF(2^3) using command
mex decode_soft.cpp -DLOG_Q=3 -I../common
and replace mex, "decode_soft.mexw64" in your main folder

**Comment by pupupu-p** [comment]
> 

Thanks for your reply!

**Comment by pupupu-p** [comment]
> Hi, just recompile mex file of decoder with Q=3 for GF(2^3) using command mex decode_soft.cpp -DLOG_Q=3 -I../common and replace mex, "decode_soft.mexw64" in your main folder

Thanks for your reply!

**Comment by Lcrypto** [comment]
You are welcome!
